"use client";
/* oxlint-disable */
import { useMemo, useRef, useState } from "react";
import { WebmcpRegistrar } from "./webmcp/registrar";
import { designMarkdown, designSystem, initialPage, validateDesign, type Block, type Change, type DesignSystem, type Page } from "../lib/design-system";
const id = (prefix: string) => `${prefix}_${Math.random().toString(36).slice(2, 8)}`;
export default function Home() {
  const [system, setSystem] = useState<DesignSystem>(designSystem), [page, setPage] = useState<Page>(initialPage), [selectedBlockId, setSelectedBlockId] = useState("block_hero"), [device, setDevice] = useState<"desktop" | "tablet" | "mobile">("desktop");
  const [changes, setChanges] = useState<Change[]>([{ id: "change_1", actor: "human", action: "Created page", detail: "Homepage · /", at: "Just now" }, { id: "change_2", actor: "agent", action: "Applied contract", detail: "Signal / Quiet Utility", at: "2 min ago" }]);
  const stateRef = useRef({ system, page, changes }); stateRef.current = { system, page, changes };
  const log = (actor: Change["actor"], action: string, detail: string) => setChanges((all) => [...all, { id: id("change"), actor, action, detail, at: "Just now" }]);
  const updateBlock = (blockId: string, patch: Partial<Block>) => { const current = stateRef.current.page.blocks.find((block) => block.id === blockId); if (!current) throw new Error("Block not found"); const next = { ...current, ...patch }; setPage((value) => ({ ...value, blocks: value.blocks.map((block) => block.id === blockId ? next : block), updatedAt: new Date().toISOString() })); setSelectedBlockId(blockId); log("agent", "Updated block", next.content.slice(0, 42)); return next; };
  const editor = useMemo(() => ({
    getSystem: () => stateRef.current.system, getPage: () => stateRef.current.page, getChanges: () => stateRef.current.changes,
    createPage: (name: string, path: string) => { const next: Page = { id: id("page"), name: name.trim(), path: path.startsWith("/") ? path : `/${path}`, blocks: [], updatedAt: new Date().toISOString() }; setPage(next); setSelectedBlockId(""); log("agent", "Created page", `${next.name} · ${next.path}`); return next; },
    insertBlock: (block: Omit<Block, "id">, index?: number) => { const next = { ...block, id: id("block") }; setPage((value) => { const blocks = [...value.blocks]; blocks.splice(Math.min(index ?? blocks.length, blocks.length), 0, next); return { ...value, blocks, updatedAt: new Date().toISOString() }; }); setSelectedBlockId(next.id); log("agent", "Inserted block", next.type); return next; },
    updateBlock,
    updateSystem: (patch: Partial<DesignSystem>) => { const next = { ...stateRef.current.system, ...patch, colors: { ...stateRef.current.system.colors, ...(patch.colors || {}) }, spacing: { ...stateRef.current.system.spacing, ...(patch.spacing || {}) }, rounded: { ...stateRef.current.system.rounded, ...(patch.rounded || {}) } }; setSystem(next); log("agent", "Updated tokens", Object.keys(patch).join(", ")); return next; },
    validate: () => validateDesign(stateRef.current.system, stateRef.current.page),
  }), []);
  const validation = validateDesign(system, page), selected = page.blocks.find((block) => block.id === selectedBlockId) || page.blocks[0];
  const mutateHuman = (patch: Partial<Block>) => { if (selected) { updateBlock(selected.id, patch); setChanges((all) => [...all.slice(0, -1), { ...all[all.length - 1], actor: "human" }]); } };
  return <main className="app-shell"><WebmcpRegistrar editor={editor} /><header className="topbar"><div className="brand-mark">DS</div><div><p className="overline">DESIGN STUDIO <span>·</span> SHARED WORKSPACE</p><h1>Build by contract.</h1></div><div className="top-actions"><span className={`health-dot ${validation.status.toLowerCase()}`} /><span className="sync-label">Synced · 2 collaborators</span><button className="button dark">Publish <span>↗</span></button></div></header>
    <section className="brief-bar"><div><span className="overline">ACTIVE BRIEF</span><strong>Signal / Quiet Utility</strong><span className="brief-copy">Calm, structured interfaces that make the rules obvious.</span></div><div className="brief-meta"><span className={`status-badge ${validation.status.toLowerCase()}`}>{validation.status}</span><span>Last edited just now</span></div></section>
    <div className="workspace"><aside className="left-rail"><div className="rail-heading"><span className="overline">PAGES</span><button className="icon-button" onClick={() => editor.createPage("Untitled page", "/untitled")}>＋</button></div><button className="page-item active"><span className="page-icon">◌</span><span><b>{page.name}</b><small>{page.path}</small></span><span className="more">···</span></button><button className="page-item muted-page" onClick={() => editor.createPage("Untitled page", "/untitled")}><span className="page-icon">+</span><span><b>Add a page</b><small>Agent-ready canvas</small></span></button><div className="rail-bottom"><span className="overline">COLLABORATORS</span><div className="avatars"><span className="avatar human">A</span><span className="avatar agent">✦</span><span className="avatar plus">+</span></div><p>Human + agent work on the same state. Every change is logged.</p></div></aside>
      <section className="canvas-area"><div className="canvas-toolbar"><div><span className="overline">CANVAS / {page.path}</span><span className="canvas-count">{page.blocks.length} blocks</span></div><div className="device-switcher">{(["desktop", "tablet", "mobile"] as const).map((item) => <button key={item} className={device === item ? "selected" : ""} onClick={() => setDevice(item)}>{item === "desktop" ? "▱" : "▯"} <span>{item}</span></button>)}</div></div><div className={`canvas-frame ${device}`} style={{ background: system.colors.paper }}><div className="canvas-page" style={{ color: system.colors.ink, fontFamily: system.typography.body.fontFamily }}>{page.blocks.map((block) => <button key={block.id} className={`canvas-block ${selectedBlockId === block.id ? "selected" : ""} block-${block.type} tone-${block.tone || "ink"}`} onClick={() => setSelectedBlockId(block.id)}>{block.type === "hero" ? <span>{block.content.split("\n").map((line) => <span key={line}>{line}</span>)}</span> : block.type === "columns" ? <span className="columns">{block.content.split("||").map((item, index) => <span key={item}><i>0{index + 1}</i>{item}</span>)}</span> : block.type === "button" ? <span className="preview-button">{block.content}<b>↗</b></span> : block.type === "divider" ? <span className="divider" /> : block.type === "image" ? <span className="image-placeholder">Image placeholder</span> : <span>{block.content}</span>}<em>{block.type}</em></button>)}</div></div><div className="canvas-footer"><span>↕ Drag blocks to reorder</span><span>⌘ K Quick actions</span><span>All values resolve from DESIGN.md</span></div></section>
      <aside className="right-rail"><div className="inspector-header"><div><span className="overline">INSPECTOR</span><h2>{selected?.type === "hero" ? "Hero block" : `${selected?.type || "Page"} block`}</h2></div><span className="agent-edit">✦ agent live</span></div>{selected && <div className="inspector-form"><label>Content<textarea value={selected.content} onChange={(event) => mutateHuman({ content: event.target.value })} /></label><label>Alignment<select value={selected.align || "left"} onChange={(event) => mutateHuman({ align: event.target.value as Block["align"] })}><option>left</option><option>center</option><option>right</option></select></label><label>Tone<div className="tone-options">{(["ink", "muted", "accent"] as const).map((tone) => <button key={tone} className={selected.tone === tone ? "selected" : ""} onClick={() => mutateHuman({ tone })}><i style={{ background: system.colors[tone === "ink" ? "ink" : tone === "muted" ? "muted" : "accent"] }} />{tone}</button>)}</div></label><div className="inspector-note"><span>↗</span><p>Changes from the agent appear here instantly. The contract validator runs on every update.</p></div></div>}<div className="contract-card"><div className="contract-card-head"><span className="overline">DESIGN.MD</span><span className={`mini-status ${validation.status.toLowerCase()}`}>{validation.status}</span></div><h3>{system.name}</h3><p>{system.description}</p><div className="token-swatches">{Object.entries(system.colors).slice(0, 5).map(([key, value]) => <button key={key} title={`Change ${key}`} style={{ background: value }} onClick={() => navigator.clipboard?.writeText(`${key}: ${value}`)}><span>{key}</span></button>)}</div><div className="contract-actions"><button onClick={() => navigator.clipboard?.writeText(designMarkdown(system))}>Copy DESIGN.md</button><button onClick={() => alert(`${validation.status}\n${validation.errors.join("\n") || "No errors"}`)}>Validate ↗</button></div></div></aside></div>
    <section className="activity-strip"><div className="activity-title"><span className="overline">LIVE ACTIVITY</span><strong>Shared change log</strong></div><div className="activity-items">{changes.slice(-3).reverse().map((change) => <div className="activity-item" key={change.id}><span className={`activity-avatar ${change.actor}`}>{change.actor === "agent" ? "✦" : "A"}</span><span><b>{change.action}</b><small>{change.detail}</small></span><time>{change.at}</time></div>)}</div><button className="view-log">View full log ↗</button></section></main>;
}
