import { defineTool } from "@nekuda/webmcp-sdk";
import { designMarkdown, type Block, type DesignSystem, type Page, type Change } from "../../lib/design-system";
export type EditorController = { getSystem: () => DesignSystem; getPage: () => Page; getChanges: () => Change[]; createPage: (name: string, path: string) => Page; insertBlock: (block: Omit<Block, "id">, index?: number) => Block; updateBlock: (blockId: string, patch: Partial<Block>) => Block; updateSystem: (patch: Partial<DesignSystem>) => DesignSystem; validate: () => Record<string, unknown> };
export function createEditorTools(editor: EditorController) { return [
  defineTool({ stableKey: "design.get_system", name: "get_design_system", title: "Leer contrato de diseño", description: "Lee el contrato visual activo y su Markdown DESIGN.md; úsala antes de crear o modificar una página para respetar colores, tipografía, espaciado, radios y componentes. Devuelve tokens, reglas y el documento fuente.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true }, async execute() { return { designSystem: editor.getSystem(), designMd: designMarkdown(editor.getSystem()), ui_effect: "design_system_inspected" }; } }),
  defineTool({ stableKey: "page.get_canvas", name: "get_canvas_state", title: "Leer canvas actual", description: "Lee la página y los bloques actualmente visibles en el canvas; úsala para entender el estado compartido antes de proponer o ejecutar cambios. Devuelve la página completa y el último estado de validación.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true }, async execute() { return { page: editor.getPage(), validation: editor.validate(), ui_effect: "canvas_inspected" }; } }),
  defineTool({ stableKey: "page.create", name: "create_design_page", title: "Crear página de diseño", description: "Crea una página nueva en el workspace visual; úsala cuando el brief requiera una nueva ruta. Devuelve la página creada y la muestra en el canvas compartido.", inputSchema: { type: "object", properties: { name: { type: "string" }, path: { type: "string" } }, required: ["name", "path"], additionalProperties: false }, async execute({ name, path }: { name: string; path: string }) { return { status: "created", page: editor.createPage(name, path), ui_effect: "page_created" }; } }),
  defineTool({ stableKey: "page.insert_block", name: "insert_design_block", title: "Insertar bloque visual", description: "Inserta un bloque en la página compartida usando los tipos permitidos por el editor; úsala para construir una composición sin saltarse la estructura visual. Devuelve el bloque y la página resultante.", inputSchema: { type: "object", properties: { type: { type: "string", enum: ["hero", "text", "button", "image", "columns", "divider"] }, content: { type: "string" }, tone: { type: "string", enum: ["ink", "muted", "accent"] }, index: { type: "integer", minimum: 0 } }, required: ["type", "content"], additionalProperties: false }, async execute({ type, content, tone, index }: { type: Block["type"]; content: string; tone?: Block["tone"]; index?: number }) { return { status: "inserted", block: editor.insertBlock({ type, content, tone }, index), page: editor.getPage(), ui_effect: "block_inserted" }; } }),
  defineTool({ stableKey: "page.update_block", name: "update_design_block", title: "Actualizar bloque visual", description: "Actualiza el contenido o propiedades de un bloque existente; úsala para iterar sobre una pieza concreta del canvas. Devuelve el bloque actualizado, la página y la validación resultante.", inputSchema: { type: "object", properties: { blockId: { type: "string" }, content: { type: "string" }, tone: { type: "string", enum: ["ink", "muted", "accent"] }, align: { type: "string", enum: ["left", "center", "right"] } }, required: ["blockId"], additionalProperties: false }, async execute({ blockId, content, tone, align }: { blockId: string; content?: string; tone?: Block["tone"]; align?: Block["align"] }) { return { status: "updated", block: editor.updateBlock(blockId, { ...(content === undefined ? {} : { content }), ...(tone === undefined ? {} : { tone }), ...(align === undefined ? {} : { align }) }), page: editor.getPage(), validation: editor.validate(), ui_effect: "block_updated" }; } }),
  defineTool({ stableKey: "design.update_tokens", name: "update_design_tokens", title: "Actualizar tokens visuales", description: "Actualiza tokens del contrato visual activo; úsala para cambiar una regla global que deba afectar de forma consistente al canvas. Devuelve el contrato actualizado y no aplica cambios si el contrato queda inválido.", inputSchema: { type: "object", properties: { colors: { type: "object" }, spacing: { type: "object" }, rounded: { type: "object" } }, additionalProperties: false }, async execute({ colors, spacing, rounded }: { colors?: Record<string, string>; spacing?: Record<string, string>; rounded?: Record<string, string> }) { const system = editor.updateSystem({ colors, spacing, rounded }); const validation = editor.validate() as { status: string }; if (validation.status === "FAILED") throw new Error("El contrato de diseño resultante no es válido"); return { status: "updated", designSystem: system, validation, ui_effect: "design_tokens_updated" }; } }),
  defineTool({ stableKey: "design.validate", name: "validate_design_contract", title: "Validar contrato y canvas", description: "Valida el contrato DESIGN.md y la página activa; úsala antes de publicar o entregar una iteración. Devuelve estado PASSED, WARNING o FAILED con errores, advertencias y contraste.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true }, async execute() { const validation = editor.validate(); return { ...validation, ui_effect: "design_validation_shown" }; } }),
  defineTool({ stableKey: "collaboration.changes", name: "get_change_log", title: "Leer historial colaborativo", description: "Lee el historial de cambios hechos por la persona y el agente sobre el diseño compartido; úsala para recuperar contexto antes de continuar una iteración. Devuelve las acciones más recientes.", inputSchema: { type: "object", properties: { limit: { type: "integer", minimum: 1, maximum: 50 } }, additionalProperties: false }, annotations: { readOnlyHint: true }, async execute({ limit }: { limit?: number }) { const changes = editor.getChanges().slice(-(limit ?? 20)).reverse(); return { changes, count: changes.length, note: changes.length ? "Historial disponible" : "El diseño todavía no tiene cambios registrados", ui_effect: "change_log_shown" }; } }),
]; }
